services:
  mysql_master:
    image: mariadb:10.3
    env_file:
      - ./master/mysql_master.env
    container_name: mysql_master
    ports:
      - 4406:3306
    volumes:
      - master_data:/var/lib/mysql
      - ./master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db:/db

  mysql_slave:
    image: mariadb:10.3
    env_file:
      - ./slave/mysql_slave.env
    container_name: mysql_slave
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - slave_data:/var/lib/mysql
      - ./slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db:/db

volumes:
  master_data:
  slave_data: